# Generated by Django 3.2.19 on 2023-08-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20230721_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'verbose_name_plural': 'Estaciones'},
        ),
        migrations.AddField(
            model_name='instrumento',
            name='serial',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
