# Generated by Django 3.2.19 on 2023-08-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_instrumento_estacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='tipo',
        ),
    ]
