# Generated by Django 3.2.19 on 2023-07-21 22:28

import ciifen.base.helpers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_auto_20230721_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pluviograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=ciifen.base.helpers.path_and_rename)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('ruta', models.CharField(max_length=50, null=True)),
                ('estacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pluviogramas', to='inventario.estacion')),
                ('instrumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pluviogramas', to='inventario.instrumento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
