# Generated by Django 3.2.19 on 2023-08-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluviograma', '0002_remove_pluviograma_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluviograma',
            name='url_serie_tiempo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pluviograma',
            name='url_trazabilidad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
