# Generated by Django 3.2.19 on 2023-08-14 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pluviograma', '0003_auto_20230812_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.DateTimeField(null=True)),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pluviograma',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pluviogramas', to='pluviograma.modelo'),
        ),
    ]
