# Generated by Django 3.2.19 on 2023-08-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluviograma', '0004_auto_20230814_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
