# Generated by Django 3.2.19 on 2023-08-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pluviograma', '0005_alter_modelo_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='minimo',
            new_name='limite_inferior',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='maximo',
        ),
    ]
