# Generated by Django 3.2.19 on 2023-08-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluviograma', '0006_auto_20230814_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='hora_inicio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
