# Generated by Django 3.2.19 on 2023-08-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluviograma', '0007_modelo_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='hora_inicio',
            field=models.TimeField(max_length=255, null=True),
        ),
    ]
